version: '3.4'

services:
  web:
    image: vaskonin/familybudgetapp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - familyBudgetApp/.env
  celery:
    image: vaskonin/familybudgetapp
    build: .
    command: celery -A familyBudgetApp worker --loglevel=info
    env_file:
      - familyBudgetApp/.env
    depends_on:
      - web
      - redis
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "%6u6ul4etA"
      POSTGRES_USER: postgres
      POSTGRES_DB: budget_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

