# Generated by Django 5.0.3 on 2024-03-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_budgetitem_monthly_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='monthly_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_items', to='budgetApp.monthlybudget'),
        ),
    ]
