# Generated by Django 5.0.3 on 2024-03-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0003_alter_budgetitem_monthly_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='yearly_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_budgets', to='budgetApp.yearlybudget'),
        ),
    ]
